
CREATE TABLE objects (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  time_stamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  parent_id INTEGER NULL REFERENCES objects(id) ON DELETE SET NULL
);

CREATE INDEX idx_objects_parent_id ON objects(parent_id);

CREATE TABLE contacts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  object_id INTEGER NOT NULL UNIQUE REFERENCES objects(id) ON DELETE CASCADE,
  server VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE INDEX idx_contacts_object_id ON contacts(object_id);
CREATE INDEX idx_contacts_email ON contacts(email);

CREATE TABLE contact_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id INTEGER NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  user_name VARCHAR(255) NOT NULL,
  CONSTRAINT uq_contact_users UNIQUE (contact_id, user_name)
);

CREATE INDEX idx_contact_users_contact_id ON contact_users(contact_id);

CREATE TABLE addresses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  object_id INTEGER NOT NULL REFERENCES objects(id) ON DELETE CASCADE,
  address_text TEXT NOT NULL
);

CREATE INDEX idx_addresses_object_id ON addresses(object_id);
